version: '3.7'

services: 
    dreamcatcher:
        build:
            context: ./
        environment: 
            OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
        ports:
        - "8080:8080"            

    jaeger:
        image: jaegertracing/all-in-one:1.22
        environment: 
            COLLECTOR_ZIPKIN_HOST_PORT: "9411"
        ports: 
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "14250:14250"
        - "9411:9411"    

networks:
    default:
        external: true
        name: jaeger